#!/bin/sh

# erst OSS probieren
aumix -L


# dann Alsa-Einstellungen
#  das längliche Argument direkt nach cset ist das zu setzende
#  "Control", dann folgt der Wert, auf den es gesetzt werden
#  soll. Liste aller Controls: "amixer controls". Jedes Control hat
#  einen Wertebereich, aus dem sein Wert sein muss (z.B. boolean oder
#  Ganzzahl 0..100). "amixer cget <control>" zeigt den Wertebereich
#  sowie den aktuellen Wert des Controls <control> an

amixer cset iface=MIXER,name='Front Playback Volume' 65%
amixer cset iface=MIXER,name='Front Playback Switch' on

amixer cset iface=MIXER,name='PCM Playback Volume' 70%

amixer cset iface=MIXER,name='Line Playback Volume' 70%
amixer cset iface=MIXER,name='Line Playback Switch' on

amixer cset iface=MIXER,name='Mic Playback Volume' 70%
amixer cset iface=MIXER,name='Mic Playback Switch' on

amixer cset iface=MIXER,name='CD Playback Volume' 70%
amixer cset iface=MIXER,name='CD Playback Switch' on

# Input-Source (index) 1 auf 1 (Line-In) setzen
#  aus irgendeinem Grund nimmt er (tack, ASRock-Board Onboard-Sound
#  snd_hda_intel) nur die Input-Source 1 auf und ignoriert
#  Input-Source 0. Mgf. Werte: 0 - Mikro, 1 - Line-In, 2 - CD (siehe
#  "amixer cget iface=MIXER,name='Input Source',index=1"). Der
#  Aufnahmepegel wird verwirrenderweise über iface=MIXER,name='Capture
#  Volume' (ohne index=1) gesetzt
amixer cset iface=MIXER,name='Input Source',index=1 1

amixer cset iface=MIXER,name='Capture Volume' 80%

# v4lctl volume 95%
v4lctl volume 70%

# TODO: dieses Skript ist jetzt spezifisch fuer tack
