#!/bin/sh

speed=4

while getopts 's:' OPTNAME; do
case "$OPTNAME" in
  "s")
    speed="$OPTARG" ;;
  "?")
    exit 1;;
esac
done

shift $(($OPTIND - 1))

if [ -z "$CDR_DEVICE" ]; then
    CDR_DEVICE="`getcdrdev`";
fi

mkisofs -f -J "$1" | cdrecord -v "-speed=$speed" dev="$CDR_DEVICE" -data -
