#!/bin/sh

#letzte Zeile von /var/log/secure ueberwachen
tail -f -n 1 /var/log/secure |
while read line; do
   #irgendwas verdaechtiges entahlten?
	echo $line|egrep 'rlogin|telnetd|sshd|pop|finger' >/dev/null &&
    (
      #aufgeregtes Gepiepe
    (
    for i in a a a a a a a a a; do
    printf '\a'; usleep 200000;
    done;
    ) &

     #Warntext auf die Console mit der kleinsten Idle-Zeit ausgeben
    who --idle | egrep '^(olaf|root)' | awk '{print $6 " " $2}' | sort | head -1 | awk '{print $2}' |
      printf "chk4rlogins: Remote access detected:\n$line\n" >/dev/`cat`;
	
	 #Warntext auch noch nach /dev/console
	printf "chk4rlogins: Remote access detected:\n$line\n" >/dev/console
  )
done

