#!/bin/sh

cat <<EOF
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
  <head>
    <title>Overview</title>
  </head>

  <body>
    <h1></h1>
EOF

find . -maxdepth 1 -mindepth 1 -name '*.jpg' -o -name '*.png' | sed 's/^..//' | sort | while read f; do
    echo "<img src=\"$f\"></img>"
done

cat <<EOF
  </body>
</html>
EOF
