#!/bin/sh

encrfile="$1"
if [ -z "$encrfile" ]; then
    echo "usage: `basename $0` <encrfile>";
    exit 1;
fi

tmpfile=/tmp/$$
umask 077;
if [ -z "$EDITOR" ]; then
    EDITOR="vi";
fi

cp -f "$encrfile" "$encrfile.bak"

echo "decrypting..." &&
gpg -o "$tmpfile" --decrypt "$encrfile" &&
$EDITOR $tmpfile &&
echo "encrypting..." &&
gpg --yes -o "$encrfile" --symmetric -a "$tmpfile"

shred -u $tmpfile || {
    echo "WARNING: shred -u $tmpfile didn't work, using rm. This might leave the decrypted data intact on the block device" >&2
    rm -f $tmpfile
}

