#!/usr/bin/perl -w

use POSIX qw(strftime);

sub datestr {
    strftime "%a %b %e %H:%M:%S %Y", localtime;
}

my $cmdstr = join(' ', map {"'$_'"} @ARGV);

print "$0: " . datestr . ": executing: $cmdstr\n";

open(STDERR, ">&STDOUT");
if (system @ARGV) {
    print "$0: " . datestr . ": failed to execute $cmdstr\n";
    exit 1;
}
else {
    print "$0: " . datestr . ": successfully executed $cmdstr\n";
    exit 0;
}
