#!/bin/sh

if [ $# -le 2 ]
then
    echo "Aufruf: ff [GrepArgs] <startdir> <regexp> <pattern>
sucht nach  <regexp> in allen Dateien, die in <startdir> (meistens '.')
oder dessen Unterverzeichnissen sind und <pattern> entsprechen.
<pattern> und evtl. <regexp> sollten in Apostrophs (') eingeschlossen sein,
damit sie nicht von der Shell expandiert werden!
[GrepArgs] sind beliebige Argumente, die intern an grep uebergeben werden.
Zum Beispiel (siehe man grep):
-i : Gross-/Kleinschreibung ignorieren
-E : nach \"richtigen\" (erweiterten) regulaeren Ausdruecken suchen
-n : Zeilennummern der Fundstellen ausgeben"
    exit
fi

GrepArgs=
nGrepArgs=$[ $# - 3 ]

n=1
while [ $n -le $nGrepArgs ]; do
    GrepArgs="$GrepArgs $1";
    shift;
    n=$[ $n + 1 ];
done

find $1 -iname "$3" -type f |
while read file; do
    # " und ' rausfiltern, da xargs sonst irgendwas von "unmatched single/double quote" faselt
    # ==> Bug in (Redhat-) xargs ?
    grep $GrepArgs "$2" "$file" | sed -e 's/"//g' -e s/\'//g | xargs -irepl echo $file: repl
done
