#!/bin/sh

set -e

ip=$(ifconfig ppp0 2>/dev/null | perl -ne "/inet addr:(.*?) / && print \$1")

if [ -n "$ip" ] && ! [[ "$ip" == 192.168.* ]]; then
  echo "$ip"
  exit 0
fi

ip=$(timeout 2 curl http://alice.box/diagnostic.htm 2>/dev/null | perl -ne "/var wan_ip='(.*?)';/ && print \$1")

if [ -n "$ip" ] && ! [[ "$ip" == 192.168.* ]] && ! [[ "$ip" == '0.0.0.0' ]]; then
  echo "$ip"
  exit 0
fi

ip=$(timeout 4 curl http://icanhazip.com 2>/dev/null)
if [ -n "$ip" ]; then
  echo "$ip"
  exit 0
fi

exit 1

