#!/bin/sh

set -e

delete=''

while getopts 'd' OPTNAME; do
case "$OPTNAME" in
  "d")
    delete=1 ;;
esac
done

shift $(($OPTIND - 1))

target="$1"

mkdir -p "$target"

# run g* binaries to avoid chicken/egg problem when this script is invoked for the 1st time

gfind /usr/local/Cellar -type l -path '*/gnubin/*' | while read f; do
    name="$(basename "$f")"
    linktarget="$(greadlink -f "$f")"
    ln -sf  "$linktarget" "$target/$name"
done

exit 0

if [[ "$delete" ]]; then
    # delete all other files in $target. Ugly hack.
    gfind "$target" -mmin +1 -print0 | xargs -0 rm -f
fi
