#!/usr/bin/perl -w

# unkorrekt, unvollstaendig


while (<STDIN>) {
    next if (/^\s*$/);

    my $comment = "";
    if (/^(.*?)\#(.*)/) {
        $_ = $1; $comment = "//$2";
    }
    s/^from +(.*?) +import +(\S+)/import $1.$2;/ && next;

    s/^(\s*)def (.*?):/$1$2 {/ and next;

    s/([A-Z]\w*?\s*\()/new $1/g;

    chomp;
    $_ = $_?"$_;$comment\n":"$comment\n";

} continue {
    print;
}
