#!/bin/sh
# identify mutiple properties of the machine or site the script is run on
# used by generate-site-specific-filenames
# should probably be named "whereami", but a program with that name already exists
# MODIFY to cover your machines/sites

if [ $# -gt 0 ]; then
  for attr in "$@"; do
    $0 | grep "^$attr:" | sed "s/^$attr://"
  done
  exit 0
fi

hostname="`hostname 2>/dev/null`"
domainname="`domainname 2>/dev/null`"

case "$domainname" in
    cs.tu-berlin.de)
        place=cs
        ;;
    isst.fhg.de)
        place=isst
        ;;
    *)
        place="unknown"
        ;;
esac


case "$hostname" in
    tick)
        place=myhomehost
        ;;
    tack)
        place=myhomedesktop
        ;;
    teck)
        place=mylaptop
        ;;
    swangoose)
        place=myissthost
        ;;
    oklischat)
	place=sys11laptop
	;;
    jumphost.*.syseleven.de)
        place=sys11jump
        ;;
esac


osname="`uname`"
osversion="`uname -r`"
arch="`uname -m`"

if [ -n "$(type -p lsb_release)" ]; then
    distr_id=$(lsb_release -si)
    distr_release=$(lsb_release -sr)
else
    distr_id='unknown'
    distr_release='unknown'
fi

cat <<EOF
place:$place
osname:$osname
osversion:$osversion
arch:$arch
distr_id:$distr_id
distr_release:$distr_release
EOF
