#!/usr/bin/perl -w

$|=1;   # autoflush stdout

use Fcntl 'SEEK_SET';

my $iface = $ARGV[0] || "eth0";

print "transferrate on interface $iface:\n";

open DEV, "</proc/net/dev" or die "couldn't open /proc/net/dev: $!";

sub getInOut {
    seek(DEV,0,SEEK_SET);
    return map { $_ =~ /^\s*$iface:(.*)/;
                 +($1 =~ /(\d+)/g)[0,8];}
             grep /^\s*$iface/,
                  <DEV>
            or die "no entry for $iface found in /proc/net/dev";
}

my ($in0,$out0,$in1,$out1);

($in0,$out0) = getInOut();

my $sleepTime=5;

while (1) {
    sleep $sleepTime;
    ($in1,$out1) = getInOut();

    print "in: ", ($in1-$in0)/$sleepTime, " bytes/s, out: ", ($out1-$out0)/$sleepTime, " bytes/s\n";
    ($in0,$out0) = ($in1,$out1);
}
