#!/usr/bin/perl -w

my $clientfifoname = "$ENV{HOME}/bin/mplayerctlclientfifo";

open(MPLAYERFIFO, "| mplayer " .join ' ', map {"'$_'"} @ARGV)
  or die "couldn't run mplayer: $!";

my $cmd;

LOOP:
while(1) {
    $cmd = `cat $clientfifoname`;
    chomp $cmd;
  SW: {
        # TODO: Cursor-Controlstrings terminalabhaengig -- curses benutzen (macht mplayer auch)?
        $cmd eq "fwd" and do { print MPLAYERFIFO "\x1b\x5b\x43"; last; };
        $cmd eq "rew" and do { print MPLAYERFIFO "\x1b\x5b\x44"; last; };
        $cmd eq "playpause" and do { print MPLAYERFIFO " "; last; };
        $cmd eq "fullscreen" and do { print MPLAYERFIFO "f"; last; };
        $cmd eq "quit" and do { print MPLAYERFIFO "q"; last LOOP; };
    }
}

# MPLAYERFIFO flushen?
