#!/bin/sh

ip="xxxxx"
while true; do
    #newip="$(cat /tmp/newip)";   #debugging
    newip=$(curl http://alice.box/diagnostic.htm 2>/dev/null | perl -ne "/var wan_ip='(.*?)';/ && print \$1");
    if [ "$newip" != "$ip" ]; then
	if [ -n "$newip" ]; then
	    logger -i "$0: WAN IP changed to $newip; publishing it.";
	    /usr/sbin/ddclient -syslog -ip "$newip" && ip="$newip";
	else
	    logger -i "$0: no WAN IP found. Won't unpublish it (it is too late, right?)";
	fi
    fi
    sleep 60;
done

