#!/bin/sh

aumix -v20 && sleep 2 &&
trap 'kill -TERM $mpg123pid; exit 0' SIGINT &&
trap 'kill -TERM $mpg123pid; exit 0' SIGTERM &&
while true; do
    mpg123 /mnt/data8/lc2-conly.mp3 &
    mpg123pid="$!";
    wait;
    sleep 1;
done
