#!/bin/sh

set -e

trap 'kill 0' EXIT
trap 'true' HUP

export PATH="/usr/local/bin:$PATH"
while true; do
    log-transferrate ppp0 20 | prepend-time >>/var/log/transferrate.log 2>&1 &
    wait "$!" || true    # HUP sent by logrotete => kill the pipe, restart loop, reopen log file and start over
    kill "$!"
done
