#!/usr/bin/env ruby

require 'rubygems'
require 'find'
require 'dbi'

["#{ENV['HOME']}/.mozilla/", "#{ENV['HOME']}/.firefox/", "#{ENV['HOME']}/.songbird2/", "#{ENV['HOME']}/Library/Application Support/Firefox/"].each do |dirname|
  next unless FileTest.exist?(dirname)
  Find.find(dirname) do |fn|
    if File.file?(fn) and "cookies.sqlite"==File.basename(fn)
      # puts "#{fn} => #{File.dirname(fn)}/cookies.txt"
      outfn = "#{File.dirname(fn)}/cookies.txt"
      existed = (FileTest.exist? outfn)
      if !existed or (File.mtime(fn) > File.mtime(outfn))
        con = DBI.connect("dbi:SQLite3:#{fn}")
        begin
          File.open(outfn,"w") do |outfile|
            con.select_all("SELECT host, path, isSecure, expiry, name, value FROM moz_cookies").each do |row|
              host,path,isSecure,expiry,name,value = row.to_a
              outfile.puts "#{host}\tTRUE\t#{path}\t#{isSecure=='0' ? 'TRUE' : 'FALSE'}\t#{expiry}\t#{name}\t#{value}"
            end
          end
        rescue
          if !existed
            File.unlink(outfn)
          end
          raise
        end
      end
    end
  end
end
