#!/bin/sh

if [ $# != 4 ]; then
  echo "usage: $0 <HM> <length in seconds> <station name> <filename prefix>" >&1
  exit 1;
fi

HM="$1";
length="$2";
station="$3";
prefix="$4";

echo "HM=$HM";
echo "length=$length";
echo "station=$station";
echo "prefix=$prefix";



while true; do
    while [ "`date +%H%M`" != $HM ]; do
	sleep 2;
    done

    xscreensaver-keepaway &
    scsvpid=$!;

    (v4lctl setstation "$station"; sleep 2; videnc.sh "$prefix-`date +%d%m%y`.avi") &

    sleep $length && killall -TERM mencoder
    kill -TERM $scsvpid;

    sleep 60;
done
