#! /bin/sh

update_cookiestxts

# Galeon
# wget --load-cookies ~/.galeon/mozilla/galeon/cookies.txt "$@"

# Firefox
wget --header='User-Agent: Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9) Gecko/2008061602 Iceweasel/3.0 (Debian-3.0~rc2-1)' --load-cookies "`find ~/.firefox/ ~/.mozilla ~/Library/Application\ Support/Firefox/ -name cookies.txt -printf '%C@ %p\n' 2>/dev/null | sort | tail -1 | sed 's/^[^ ]* *//'`" "$@"
