#!/usr/bin/ruby -w
# IN: - lines with y0 y1 ....yn   on stdin
#     - (optional) ytitle0 ytitle1 ... ytitlen   on command line
#
# OUT: gnuplot script for plotting that data on stdout. x axis
#      contains the line number, starting with 1

samples = STDIN.readlines.map{|l|l.split}
n_graphs = samples[0].length
case ARGV.length
when n_graphs
  ytitles = ARGV
when 0
  ytitles = (0...n_graphs).map{|i| "variable #{i}"}
else
  raise "unmatching arguments (must be either none or ytitle0, ytitle1, ...)"
end

# puts %Q{set xlabel "#{xtitle}"} if xtitle
puts "plot #{ytitles.map{|title| "'-' with lines title '#{title}'"}.join(',')}"

(0...n_graphs).each do |y_idx|
  samples.each do |sample|
    puts "#{sample[y_idx]}"
  end
  puts "e"
end
