#!/bin/sh
# vorher (als root):
#  eval `ssh-agent -s`
#  ssh-add ~/.ssh/id_dsa

while true; do
    /usr/local/sbin/myissthost/run-isstsshvpn;
    sleep 620;
done 2>&1 | tee -a /var/log/run-isstsshvpn.log
