#!/bin/sh
# pre: - eth0 up and connected to the IPv4 internet
#
# post: - tun6to4 up and connected to the IPv6 internet, with IPv6
#         address = 2002:<eth0's IPv4 address>::1:2

set -e

execlogged() {
  echo "executing: $@" && eval "$@"

}

echo "IPv6 aktivieren..."

# set up eth0
execlogged ip tunnel add tun6to4 mode sit remote any local "`ifaceaddr eth0`"
execlogged ip link set dev tun6to4 up
execlogged ip -6 addr add "`ip6to4 eth0`::1:2" dev tun6to4
execlogged ip -6 route add 2000::/3 via ::192.88.99.1 dev tun6to4 metric 1
