#!/bin/sh

dev="`ifconfig | grepre '^(ppp\d+)' | tail -1`"

if [ "$dev" = "ppp0" -o -z "$dev" ]; then
  echo "$0: no VPN interface running"
  exit 1
fi

route add -host 153.97.73.127 dev ppp0
route add -net 192.102.0.0 netmask 255.255.0.0 gw 192.168.3.2 dev $dev
route add -net 153.97.0.0 netmask 255.255.0.0 gw 192.168.3.2 dev $dev
route add -host 129.26.8.213 gw 192.168.3.2 dev $dev # news.fhg.de
route add -host ftp.isst.fhg.de dev ppp0  # ssh-Loginserver im ISST (direkt von außen erreichbar => schneller)
