#!/bin/sh

log_msg() {
    date "+%c: $*" >&2
}

oldip="`get_wan_ip`"
while true; do
  ip="`get_wan_ip`"
  if ! [ "$ip" = "$oldip" ]; then
    log_msg "DSL IP change detected: $oldip -> $ip. Killing VPN";
    kill-vpn.sh
  fi
  oldip="$ip"

  sleep 60
done
