#!/bin/sh
# post: no global IPv6 addresses on either lanif or tun6to4

addr="`ifaceaddr lanif | egrep '^2002' | head -1`"
while [ -n "$addr" ]; do
    ip addr del "$addr" dev lanif
    addr="`ifaceaddr lanif | egrep '^2002' | head -1`"
done

route="`route -6 | awk '/^2002/ {print $1}' | head -1`"
while [ -n "$route" ]; do
    ip -6 route del "$route"
    route="`route -6 | awk '/^2002/ {print $1}' | head -1`"
done
ip tunnel del tun6to4
