#!/bin/sh

set -e

umount /mnt/backup1 || true
cryptsetup close /dev/mapper/backup1_crypt || true
cryptsetup open --type luks /dev/disk/by-id/ata-ST2000DM001-1E6164_Z1E7RKAL-part1 backup1_crypt
mount /mnt/backup1
